require('basic')
require("keybindings")
require("plugins")
require("colorscheme")
require("plugin-nvim-tree")
require("plugin-nvim-treesitter")
require("plugin-bufferline")
require("plugin-lualine")
require("plugin-telescope")
require("plugin-dashboard")
require("plugin-project")

require("lsp.setup")
require("lsp.cmp")
